project: omnilrs/omni-tests
version: 0.1.0

jobs:
  test-startup:
    type: test
    timeout: 30 # minutes
    package:
      docker:
        build:
          dockerfile: ./artefacts.Dockerfile
    runtime:
      framework: other
      simulator: isaacsim

    scenarios:
      settings:
        - name: test_ros2_sanity
          run: "pixi run test-ros2"
        - name: test_ros2_sanity_largescale
          run: "pixi run test-ros2-largescale"
        - name: test_yamcs_sanity
          run: "pixi run test-yamcs"
        - name: test_yamcs_sanity_largescale
          run: "pixi run test-yamcs-largescale"
